version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nftickets_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nftickets_network

volumes:
  postgres_data:

networks:
  nftickets_network:
