version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Adjust the ports as needed for your application
    volumes:
      - .:/app
      - ../web3:/app/web3
      - /app/node_modules # Avoid conflicts with local `
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm start