version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Adjust the ports as needed for your application
    volumes:
      - .:/app
      - /app/node_modules # Avoid conflicts with local `node_modules`
    environment:
      - NODE_ENV=development # Add any environment variables needed
    command: npm start
